#!/bin/bash

echo "=================================================="
echo "Intents UI Extension 自动配置脚本"
echo "=================================================="
echo ""

PROJECT_DIR="/Users/linjx/Desktop/kapi/AppIntent"
XCODE_PROJECT="$PROJECT_DIR/AppIntent.xcodeproj"

echo "✅ 准备工作已完成："
echo "   - IntentViewController.swift"
echo "   - Info.plist"
echo "   - MainInterface.storyboard"
echo "   - ShowExpenseIntentUI.entitlements"
echo ""
echo "📋 请按照以下步骤在 Xcode 中手动添加 Target："
echo ""
echo "1️⃣  打开 Xcode 项目："
echo "   open '$XCODE_PROJECT'"
echo ""
echo "2️⃣  添加新 Target："
echo "   - File → New → Target..."
echo "   - 选择 iOS → Intents UI Extension"
echo "   - Product Name: ShowExpenseIntentUI"
echo "   - Language: Swift"
echo "   - 取消勾选 'Include Configuration Intent'"
echo "   - 点击 Finish"
echo ""
echo "3️⃣  删除自动生成的文件："
echo "   Xcode 会在 ShowExpenseIntentUI 文件夹中创建一些文件"
echo "   删除这些自动生成的文件（我们使用已准备好的）"
echo ""
echo "4️⃣  移动准备好的文件："
echo "   将以下文件移动到 Xcode 创建的 ShowExpenseIntentUI 文件夹中："
echo "   - IntentViewController.swift"
echo "   - Info.plist"
echo "   - MainInterface.storyboard"
echo "   - ShowExpenseIntentUI.entitlements"
echo ""
echo "5️⃣  配置 Target："
echo "   a. 选择 ShowExpenseIntentUI target"
echo "   b. Signing & Capabilities:"
echo "      - 添加 App Groups capability"
echo "      - 勾选 group.com.dm.AppIntent"
echo "   c. Build Settings:"
echo "      - Code Signing Entitlements: ShowExpenseIntentUI/ShowExpenseIntentUI.entitlements"
echo "   d. Build Phases → Link Binary With Libraries:"
echo "      - 添加 IntentsUI.framework"
echo ""
echo "6️⃣  验证配置："
echo "   a. 确保 Info.plist 中包含："
echo "      <key>IntentsSupported</key>"
echo "      <array>"
echo "          <string>ShowExpenseIntent</string>"
echo "      </array>"
echo ""
echo "   b. 确保 MainInterface.storyboard 的 Initial View Controller"
echo "      指向 IntentViewController"
echo ""
echo "7️⃣  构建项目："
echo "   Product → Build (⌘B)"
echo ""
echo "=================================================="
echo "现在打开 Xcode 吗? (y/n)"
read -r response

if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    echo "正在打开 Xcode..."
    open "$XCODE_PROJECT"
    echo "✅ Xcode 已打开，请按照上述步骤操作"
else
    echo "手动打开项目："
    echo "open '$XCODE_PROJECT'"
fi

echo ""
echo "配置完成后，查看详细文档："
echo "cat '$PROJECT_DIR/INTENTS_UI_SETUP.md'"
